### ISSUE TITLE
Wrong value kube.tf.example hcloud_k3s.source

### ISSUE THREAD

**Issue by lokhmakov** [okami101/terraform-hcloud-k3s#1]
Current: `okami101/hcloud-k3s`
Terraform registry: `okami101/k3s/hcloud`

**Comment by adr1enbe4udou1n** [comment]
Thx for feedback !

Also for `control_planes_custom_config`, I added [this link](https://docs.k3s.io/cli/server) as reference.
So you can use `tls-san` for exemple inside it.
